SELECT * FROM spend.category;
insert into category(name, merchant) values ("Subway", "Restaurants");
insert into category(name, merchant) values ("Nordstrom", "Department Stores");
insert into category(name, merchant) values ("Macy", "Department Stores");
insert into category(name, merchant) values ("Chipotle", "Restaurants");
insert into category(name, merchant) values ("H Mart", "Supermarket");
insert into category(name, merchant) values ("Trader Joe\'s", "Supermarket");
insert into category(name, merchant) values ("Wholesome Choice", "Supermarket");
insert into category(name, merchant) values ("Costco", "Supermarket");
insert into category(name, merchant) values ("USA Gasoline", "Gasoline");
insert into category(name, merchant) values ("Target", "Supermarket");
insert into category(name, merchant) values ("Metro Express ", "Service");
insert into category(name, merchant) values ("Trader Joe's", "Supermarket");
insert into category(name, merchant) values ("Crown Ace Hardware", "Merchandise/retail");
insert into category(name, merchant) values ("99 Ranch", "Supermarket");
insert into category(name, merchant) values ("IZOD", "Merchandise/retail");
insert into category(name, merchant) values ("Panda Express", "Restaurant");
insert into category(name, merchant) values ("Tommy Hilfiger", "Merchandise/retail");
Delete from category;